In [ ]:
import pandas as pd

In [1]:
import pandas as pd

def load_exam_review_skiprows():
    """Load exam review data from a CSV file with a custom separator '>' and skip the first 2 rows.

    Returns:
        pd.DataFrame: DataFrame containing the exam review data.
    """
    url = 'https://gitlab.crio.do/public_content/da-ds-datasets/pyt-102-datasets/-/raw/main/exam_review.csv'
    return pd.read_csv(url, sep='>', skiprows=2, engine='python')
load_exam_review_skiprows()

   Melvin   Scott  24      77  83
0  Amirah   Haley  22      92  67
1  Gerard   Mills  19  78,000  72
2     Amy  Grimes  23      91  81

In [2]:
# Do not edit this cell
def test_load_exam_review_skiprows():
    """Test function for load_exam_review_skiprows to verify correct data loading and skipped rows."""
    full_df = pd.read_csv('https://gitlab.crio.do/public_content/da-ds-datasets/pyt-102-datasets/-/raw/main/exam_review.csv', sep='>')
    exam_df = load_exam_review_skiprows()
    assert len(exam_df) == len(full_df) - 2, "Skipping rows failed: Row count mismatch"
    print("✅ Test Passed: Exam review data loaded successfully, and first 2 rows were skipped.")
    print(exam_df.head())

# Run the test function
test_load_exam_review_skiprows()

✅ Test Passed: Exam review data loaded successfully, and first 2 rows were skipped.
   Melvin   Scott  24      77  83
0  Amirah   Haley  22      92  67
1  Gerard   Mills  19  78,000  72
2     Amy  Grimes  23      91  81

In [3]:
def load_exam_review_skip_specific_rows():
    """Load exam review data from a CSV file with a custom separator '>' and skip specific rows (1 and 3).

    Returns:
        pd.DataFrame: DataFrame containing the exam review data.
    """
    url = 'https://gitlab.crio.do/public_content/da-ds-datasets/pyt-102-datasets/-/raw/main/exam_review.csv'
    return pd.read_csv(url, sep='>', skiprows=[1, 3], engine='python')
load_exam_review_skip_specific_rows()

  first_name last_name  age math_score  french_score
0     Melvin     Scott   24         77            83
1     Gerard     Mills   19     78,000            72
2        Amy    Grimes   23         91            81

In [4]:
# Do not edit this cell
def test_load_exam_review_skip_specific_rows():
    """Test function for load_exam_review_skip_specific_rows to verify correct data loading, column count, and skipped rows."""
    full_df = pd.read_csv('https://gitlab.crio.do/public_content/da-ds-datasets/pyt-102-datasets/-/raw/main/exam_review.csv', sep='>', skip_blank_lines=False)
    exam_df = load_exam_review_skip_specific_rows()
    assert not exam_df.empty, "Exam review data loading failed (custom separator '>', skipping rows [1,3])"
    assert exam_df.shape[1] == 5, f"Column count mismatch: Expected 5, but found {exam_df.shape[1]}"
    skipped_rows = full_df.iloc[[1, 3]]
    for _, skipped_row in skipped_rows.iterrows():
        assert not (exam_df == skipped_row).all(axis=1).any(), f"Skipping rows failed: Row {skipped_row} still exists in the dataset."
    print("✅ Test Passed: Exam review data loaded successfully, with correct column count (5), and rows [1,3] were skipped.")
    print(exam_df.head())

# Run the test function
test_load_exam_review_skip_specific_rows()

✅ Test Passed: Exam review data loaded successfully, with correct column count (5), and rows [1,3] were skipped.
  first_name last_name  age math_score  french_score
0     Melvin     Scott   24         77            83
1     Gerard     Mills   19     78,000            72
2        Amy    Grimes   23         91            81