In [15]:
import pandas as pd
import inspect

In [16]:


def create_country_dataframe():
    """
    Creates a Pandas DataFrame with country-related data and prints its information.

    Returns:
        pd.DataFrame: The created DataFrame.
    """
    data = {
        'Population': [35.467, 63.951, 80.94, 60.665, 127.061, 64.511, 318.523],
        'GDP': [1785387, 2833687, 3874437, 2167744, 4602367, 2950039, 17348075],
        'Surface Area': [9984670, 640679, 357114, 301336, 377930, 242495, 9525067],
        'HDI': [0.913, 0.888, 0.916, 0.873, 0.891, 0.907, 0.915],
        'Continent': ['America', 'Europe', 'Europe', 'Europe', 'Asia', 'Europe', 'America']
    }
    countries = ["Canada", "France", "Germany", "Italy", "Japan", "United Kingdom", "United States"]
    df = pd.DataFrame(data, index=countries)
    df.info()
    return df
create_country_dataframe()

<class 'pandas.core.frame.DataFrame'>
Index: 7 entries, Canada to United States
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Population    7 non-null      float64
 1   GDP           7 non-null      int64
 2   Surface Area  7 non-null      int64
 3   HDI           7 non-null      float64
 4   Continent     7 non-null      object
dtypes: float64(2), int64(2), object(1)
memory usage: 336.0+ bytes

                Population       GDP  Surface Area    HDI Continent
Canada              35.467   1785387       9984670  0.913   America
France              63.951   2833687        640679  0.888    Europe
Germany             80.940   3874437        357114  0.916    Europe
Italy               60.665   2167744        301336  0.873    Europe
Japan              127.061   4602367        377930  0.891      Asia
United Kingdom      64.511   2950039        242495  0.907    Europe
United States      318.523  17348075       9525067  0.915   America

In [17]:
def test_create_country_dataframe():
    """Test if df.info() is called and a DataFrame is returned."""
    # Check if df.info() is used in the function
    source_code = inspect.getsource(create_country_dataframe)
    assert ".info()" in source_code, "df.info() is not called in the function"

    # Check if the function returns a DataFrame
    df = create_country_dataframe()
    assert isinstance(df, pd.DataFrame), "Function did not return a DataFrame"

    print("✅ Test Passed: create_country_dataframe() is implemented correctly.")

test_create_country_dataframe()

<class 'pandas.core.frame.DataFrame'>
Index: 7 entries, Canada to United States
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Population    7 non-null      float64
 1   GDP           7 non-null      int64
 2   Surface Area  7 non-null      int64
 3   HDI           7 non-null      float64
 4   Continent     7 non-null      object
dtypes: float64(2), int64(2), object(1)
memory usage: 336.0+ bytes
✅ Test Passed: create_country_dataframe() is implemented correctly.

In [18]:
import pandas as pd

def describe_country_dataframe():
    """
    Creates a Pandas DataFrame with country-related data and prints its descriptive statistics.

    Returns:
        pd.DataFrame: The created DataFrame.
    """
    data = {
        'Population': [35.467, 63.951, 80.94, 60.665, 127.061, 64.511, 318.523],
        'GDP': [1785387, 2833687, 3874437, 2167744, 4602367, 2950039, 17348075],
        'Surface Area': [9984670, 640679, 357114, 301336, 377930, 242495, 9525067],
        'HDI': [0.913, 0.888, 0.916, 0.873, 0.891, 0.907, 0.915],
        'Continent': ['America', 'Europe', 'Europe', 'Europe', 'Asia', 'Europe', 'America']
    }
    countries = ["Canada", "France", "Germany", "Italy", "Japan", "United Kingdom", "United States"]
    df = pd.DataFrame(data, index=countries)
    print(df.describe())
    return df
describe_country_dataframe()

       Population           GDP  Surface Area       HDI
count    7.000000  7.000000e+00  7.000000e+00  7.000000
mean   107.302571  5.080248e+06  3.061327e+06  0.900429
std     97.249970  5.494020e+06  4.576187e+06  0.016592
min     35.467000  1.785387e+06  2.424950e+05  0.873000
25%     62.308000  2.500716e+06  3.292250e+05  0.889500
50%     64.511000  2.950039e+06  3.779300e+05  0.907000
75%    104.000500  4.238402e+06  5.082873e+06  0.914000
max    318.523000  1.734808e+07  9.984670e+06  0.916000

                Population       GDP  Surface Area    HDI Continent
Canada              35.467   1785387       9984670  0.913   America
France              63.951   2833687        640679  0.888    Europe
Germany             80.940   3874437        357114  0.916    Europe
Italy               60.665   2167744        301336  0.873    Europe
Japan              127.061   4602367        377930  0.891      Asia
United Kingdom      64.511   2950039        242495  0.907    Europe
United States      318.523  17348075       9525067  0.915   America

In [19]:
def test_describe_country_dataframe():
    """Test if df.describe() is called and a DataFrame is returned."""
    # Check if df.describe() is used in the function
    source_code = inspect.getsource(describe_country_dataframe)
    assert ".describe()" in source_code, "df.describe() is not called in the function"

    # Check if the function returns a DataFrame
    df = describe_country_dataframe()
    assert isinstance(df, pd.DataFrame), "Function did not return a DataFrame"

    print("✅ Test Passed: describe_country_dataframe() is implemented correctly.")

test_describe_country_dataframe()

       Population           GDP  Surface Area       HDI
count    7.000000  7.000000e+00  7.000000e+00  7.000000
mean   107.302571  5.080248e+06  3.061327e+06  0.900429
std     97.249970  5.494020e+06  4.576187e+06  0.016592
min     35.467000  1.785387e+06  2.424950e+05  0.873000
25%     62.308000  2.500716e+06  3.292250e+05  0.889500
50%     64.511000  2.950039e+06  3.779300e+05  0.907000
75%    104.000500  4.238402e+06  5.082873e+06  0.914000
max    318.523000  1.734808e+07  9.984670e+06  0.916000
✅ Test Passed: describe_country_dataframe() is implemented correctly.