In [ ]:
import pandas as pd

In [53]:
import pandas as pd

def load_btc_market_price():
    """
    Loads BTC market price data from a CSV file.

    Returns:
        pd.DataFrame: DataFrame containing the loaded data.
    """
    url = 'https://gitlab.crio.do/public_content/da-ds-datasets/pyt-102-datasets/-/raw/main/btc-market-price.csv'
    return pd.read_csv(url)
load_btc_market_price()

      2/4/17 0:00  1099.169125
0     3/4/17 0:00     1141.813
1     4/4/17 0:00            ?
2     5/4/17 0:00  1133.079314
3     6/4/17 0:00            -
4     7/4/17 0:00            -
..            ...          ...
359  28/3/18 0:00      7960.38
360  29/3/18 0:00      7172.28
361  30/3/18 0:00  6882.531667
362  31/3/18 0:00      6935.48
363   1/4/18 0:00     6794.105

[364 rows x 2 columns]

In [54]:
# Do not edit this cell
def test_load_btc_market_price():
    """Test function for load_btc_market_price to verify correct data loading."""
    btc_data = load_btc_market_price()
    assert not btc_data.empty, "BTC market price data loading failed"
    print("✅ Test Passed: BTC market price data loaded successfully.")
    print(btc_data.head())

# Run the test function
test_load_btc_market_price()

✅ Test Passed: BTC market price data loaded successfully.
   2/4/17 0:00  1099.169125
0  3/4/17 0:00     1141.813
1  4/4/17 0:00            ?
2  5/4/17 0:00  1133.079314
3  6/4/17 0:00            -
4  7/4/17 0:00            -

In [55]:
def load_btc_market_price_no_header():
    """
    Loads BTC market price data from a CSV file without any header.

    Returns:
        pd.DataFrame: DataFrame containing the loaded data without header.
    """
    url = 'https://gitlab.crio.do/public_content/da-ds-datasets/pyt-102-datasets/-/raw/main/btc-market-price.csv'
    return pd.read_csv(url, header=None)
load_btc_market_price_no_header()

                0            1
0     2/4/17 0:00  1099.169125
1     3/4/17 0:00     1141.813
2     4/4/17 0:00            ?
3     5/4/17 0:00  1133.079314
4     6/4/17 0:00            -
..            ...          ...
360  28/3/18 0:00      7960.38
361  29/3/18 0:00      7172.28
362  30/3/18 0:00  6882.531667
363  31/3/18 0:00      6935.48
364   1/4/18 0:00     6794.105

[365 rows x 2 columns]

In [56]:
# Do not edit this cell
def test_load_btc_market_price_no_header():
    """Test function for load_btc_market_price_no_header to verify correct data loading."""
    btc_data = load_btc_market_price_no_header()
    assert not btc_data.empty, "BTC market price data loading failed (no header)"
    print("✅ Test Passed: BTC market price data (no header) loaded successfully.")
    print(btc_data.head())

# Run the test function
test_load_btc_market_price_no_header()

✅ Test Passed: BTC market price data (no header) loaded successfully.
             0            1
0  2/4/17 0:00  1099.169125
1  3/4/17 0:00     1141.813
2  4/4/17 0:00            ?
3  5/4/17 0:00  1133.079314
4  6/4/17 0:00            -

In [57]:
def load_btc_market_price_with_names():
    """
    Loads BTC market price data from a CSV file with custom column names.

    Returns:
        pd.DataFrame: DataFrame containing the loaded data with custom column names.
    """
    url = 'https://gitlab.crio.do/public_content/da-ds-datasets/pyt-102-datasets/-/raw/main/btc-market-price.csv'
    df = pd.read_csv(url, header=None)
    df.columns = ['Timestamp', 'Price']
    return df
load_btc_market_price_with_names()

        Timestamp        Price
0     2/4/17 0:00  1099.169125
1     3/4/17 0:00     1141.813
2     4/4/17 0:00            ?
3     5/4/17 0:00  1133.079314
4     6/4/17 0:00            -
..            ...          ...
360  28/3/18 0:00      7960.38
361  29/3/18 0:00      7172.28
362  30/3/18 0:00  6882.531667
363  31/3/18 0:00      6935.48
364   1/4/18 0:00     6794.105

[365 rows x 2 columns]

In [58]:
# Do not edit this cell
def test_load_btc_market_price_with_names():
    """Test function for load_btc_market_price_with_names to verify correct data loading."""
    btc_data = load_btc_market_price_with_names()
    assert not btc_data.empty, "BTC market price data loading failed (with column names)"
    print("✅ Test Passed: BTC market price data (with column names) loaded successfully.")
    print(btc_data.head())

# Run the test function
test_load_btc_market_price_with_names()

✅ Test Passed: BTC market price data (with column names) loaded successfully.
     Timestamp        Price
0  2/4/17 0:00  1099.169125
1  3/4/17 0:00     1141.813
2  4/4/17 0:00            ?
3  5/4/17 0:00  1133.079314
4  6/4/17 0:00            -