# Product Category Analysis
This notebook processes the product categories dataset by listing unique categories and counting occurrences.

## Load the Dataset

In [6]:
import pandas as pd

# Load the dataset
file_path = 'https://gitlab.crio.do/public_content/da-ds-datasets/pyt-102-datasets/-/raw/main/product_categories_data.csv'
df = pd.read_csv(file_path)

# Display first few rows
df.head()  # TODO: Ensure dataset loads correctly

      Product     Category
0       Couch    Furniture
1     Blender    Furniture
2  Smartphone   Stationery
3     Blender        Books
4         Pen  Electronics

## Implement the Category Analysis Function

In [10]:
import pandas as pd

def analyze_product_categories(df):
    """
    Analyze the product categories dataset to list unique categories and count occurrences.

    Parameters:
    df (pd.DataFrame): DataFrame containing 'Product' and 'Category' columns.

    Returns:
    tuple: List of unique categories and a DataFrame of category counts.
    """
    if df.empty:
        return [], pd.DataFrame(columns=['Category', 'Count'])

    # List unique categories
    unique_categories = df['Category'].unique()

    # Count occurrences of each category
    category_counts = df['Category'].value_counts().reset_index()
    category_counts.columns = ['Category', 'Count']

    return unique_categories, category_counts

# Sample usage
url = "https://gitlab.crio.do/public_content/da-ds-datasets/pyt-102-datasets/-/raw/main/product_categories_data.csv"
df = pd.read_csv(url)

unique_categories, category_counts = analyze_product_categories(df)

print("Unique Categories:")
print(unique_categories)
print("\nCategory Counts:")
print(category_counts)

Unique Categories:
['Furniture' 'Stationery' 'Books' 'Electronics' 'Home']

Category Counts:
      Category  Count
0   Stationery     22
1    Furniture     21
2         Home     20
3  Electronics     19
4        Books     18

## Apply the Analysis Function and Display Results

In [11]:
# Apply analysis function
unique_categories, df_category_counts = analyze_product_categories(df)  # TODO: Ensure function implementation

# Display the results
print(f"Unique Categories: {unique_categories}")  # TODO: Verify output
df_category_counts.head()  # TODO: Ensure correct category count output

Unique Categories: ['Furniture' 'Stationery' 'Books' 'Electronics' 'Home']

      Category  Count
0   Stationery     22
1    Furniture     21
2         Home     20
3  Electronics     19
4        Books     18

## Run Tests

In [12]:
# Test: Checking unique categories and category count output
test_data = pd.DataFrame({
    'Product': ['Item1', 'Item2', 'Item3', 'Item4', 'Item5', 'Item6'],
    'Category': ['Food', 'Food', 'Clothing', 'Clothing', 'Electronics', 'Electronics']
})

expected_unique_categories = ['Food', 'Clothing', 'Electronics']
expected_category_counts = {'Food': 2, 'Clothing': 2, 'Electronics': 2}

try:
    unique_categories, df_category_counts = analyze_product_categories(test_data)
    assert set(unique_categories) == set(expected_unique_categories), f"Expected {expected_unique_categories}, but got {unique_categories}"
    assert df_category_counts.set_index('Category')['Count'].to_dict() == expected_category_counts, f"Expected {expected_category_counts}, but got {df_category_counts.to_dict()}"
    print("**✅ Test Passed:** Category analysis is correct.")
except Exception as e:
    print(f"**❌ Test Failed:** {e}")

**✅ Test Passed:** Category analysis is correct.