# Product Sales Ranking
This notebook processes the product sales dataset by ranking products based on their sales figures and selecting the top N products.

## Load the Dataset

In [5]:
import pandas as pd

# Load the dataset
file_path = 'https://gitlab.crio.do/public_content/da-ds-datasets/pyt-102-datasets/-/raw/main/product_sales_dataset.csv'
df = pd.read_csv(file_path)

# Display first few rows
df.head()  # TODO: Ensure dataset loads correctly

      Product     Category  Sales
0          TV    Furniture   2079
1     Blender         Home   3551
2  Smartphone    Furniture   2158
3        Book  Electronics   3948
4      Laptop    Furniture   4438

## Implement the Product Ranking Function

In [6]:
import pandas as pd

def rank_top_products(df, top_n=3):
    """
    Rank products based on their sales figures and select the top N products.

    Parameters:
    df (pd.DataFrame): DataFrame containing 'Product', 'Category', and 'Sales' columns.
    top_n (int): Number of top products to return.

    Returns:
    pd.DataFrame: Ranked DataFrame containing top N products.
    """
    # Ensure 'Sales' is numeric
    df['Sales'] = pd.to_numeric(df['Sales'], errors='coerce')

    # Rank products based on 'Sales' in descending order
    df['Rank'] = df['Sales'].rank(ascending=False, method='min')

    # Filter top N products
    top_products = df[df['Rank'] <= top_n].sort_values(by='Rank')

    # Return the top N products with 'Product', 'Sales', and 'Rank'
    return top_products[['Product', 'Sales', 'Rank']]

# Sample usage
url = "https://gitlab.crio.do/public_content/da-ds-datasets/pyt-102-datasets/-/raw/main/product_sales_dataset.csv"
df = pd.read_csv(url)
top_n = 3
top_products = rank_top_products(df, top_n)
print(top_products)

    Product  Sales  Rank
12     Oven   4773   1.0
56     Oven   4773   1.0
100    Oven   4773   1.0

## Apply the Ranking Function and Display Results

In [7]:
# Apply ranking function
df_top_products = rank_top_products(df, top_n=3)  # TODO: Ensure function implementation

# Display the top ranked products DataFrame
df_top_products.head()  # TODO: Verify ranking results

    Product  Sales  Rank
12     Oven   4773   1.0
56     Oven   4773   1.0
100    Oven   4773   1.0

## Run Tests

In [8]:
import pandas as pd

# Test: Checking top product ranking output
test_data = pd.DataFrame({
    'Product': ['Laptop', 'Phone', 'Shoes', 'TV', 'Tablet', 'Watch'],
    'Category': ['Electronics', 'Electronics', 'Fashion', 'Electronics', 'Electronics', 'Electronics'],
    'Sales': [1500, 900, 2000, 1200, 800, 3000]
})

expected_top_products = pd.DataFrame({
    'Product': ['Watch', 'Shoes', 'Laptop'],
    'Sales': [3000, 2000, 1500],
    'Rank': [1, 2, 3]
})

try:
    df_result = rank_top_products(test_data, top_n=3)

    # Reset index, sort by Product, and ensure Rank is int type
    df_result_sorted = df_result[['Product', 'Sales', 'Rank']].sort_values(by='Product').reset_index(drop=True)
    df_result_sorted['Rank'] = df_result_sorted['Rank'].astype(int)

    expected_sorted = expected_top_products.sort_values(by='Product').reset_index(drop=True)

    assert df_result_sorted.equals(expected_sorted), f"Expected:\n{expected_sorted}\nGot:\n{df_result_sorted}"
    print("✅ Test Passed: Top product ranking is correct.")
except Exception as e:
    print(f"❌ Test Failed: {e}")

✅ Test Passed: Top product ranking is correct.